# Common to all distros
common_software:
  - git
  - wget
  - tree
  - tar
  - python3-pip
  - ansible-core
  - sshpass

# ansible_distribution_file_variety
base_software:
  Debian:
    - dnsutils
    - build-essential
    - python3-dev
  RedHat:
    - bind-utils
    - gcc
    - python3-devel

python_libraries:
  - ipaddress

ansible_collections:
  - arista.eos:4.1.2
  - community.network:3.1.0
  - ansible.posix:1.3.0

software_additional: []

docker_repo_url: https://download.docker.com/linux
