scrape_configs:
  - job_name: 'bgp-ping'
    scrape_interval: 10s
    static_configs:
      - targets: ['clab-netgo-host-2:9313']
  - job_name: 'event-trigger'
    scrape_interval: 10s
    static_configs:
      - targets: ['clab-netgo-host-3:9313']
