- name: Run NVIDIA Go module on Linux [{{ ansible_system }}]
  cumulus_linux:
    host: "{{ ansible_host }}"
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    file: "{{ ansible_file }}"
  register: output