- name: Create SSH Key Pair
  include_tasks: create_key_pair.yml

- name: Create VPC
  include_tasks: create_vpc.yml

- name: Create Security Group
  include_tasks: create_security_group.yml

- name: Create Subnet
  include_tasks: create_subnet.yml

- name: Create Internet Gateway
  include_tasks: create_igw.yml

- name: Create Route Table
  include_tasks: create_rt_table.yml

- name: Provision EC2 Instance
  include_tasks: create_ec2_instance.yml

- name: Get EC2 info (and retry to give it time to get the public IP address)
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ ec2_name_tag }}"
      "tag:Environment": "{{ ec2_environment }}"
      # 0 (pending), 16 (running), 32 (shutting-down), 48 (terminated), 64 (stopping), and 80 (stopped)
      instance-state-code: [ "0", "16" ]
  register: ec2
  until: ec2.instances[0].public_ip_address is defined
  retries: 30
  delay: 10

- name: Save access details
  ansible.builtin.set_fact:
    ssh_info: "ssh -i {{ temp_dir }}/{{ ssh_key_filename }} {{ ec2_username }}@{{ ec2.instances[0].public_dns_name }}"

- name: Wait until we can SSH to the instance
  ansible.builtin.wait_for:
    host: "{{ ec2.instances[0].public_ip_address }}"
    port: 22
    state: started