- name: First Play - Configure Routers
  hosts: routers
  gather_facts: false
  vars_files:
    - eos/input.yml
  vars:
    go: true

  tasks:
    - name: Run Nokia Go module on Systems without Go installed
      go_srl:
        host: localhost
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ hostvars[inventory_hostname] | string | b64encode }}"
      when: ('srl' in group_names) and not go

    - name: Run Nokia Go module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ hostvars[inventory_hostname] | string | b64encode }}"
      delegate_to: localhost
      when: ('srl' in group_names) and go

    - name: Run NVIDIA Go module on Systems without Go installed
      go_cvx:
        host: localhost
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ hostvars[inventory_hostname] | string | b64encode }}"
      when: ('cvx' in group_names) and not go

    - name: Run NVIDIA Go module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ hostvars[inventory_hostname] | string | b64encode }}"
      delegate_to: localhost
      when: ('cvx' in group_names) and go



- name: Second Play - Validate changes
  hosts: localhost
  gather_facts: false
  vars:
    go: true

  tasks:
    - name: Run Validate module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
      when: go
