- name: First Play - Configure Routers
  hosts: routers
  gather_facts: true
  vars_files:
    - eos/input.yml
  vars:
    in_cvx: "{{ lookup('file', 'cvx/input.yml') }}"
    in_srl: "{{ lookup('file', 'srl/input.yml') }}"
    go: true

  tasks:
    - name: Run Nokia Go module on Systems without Go installed
      go_srl:
        host: localhost
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ in_srl | string | b64encode }}"
      when: ('srl' in group_names) and not go

    - name: Run Nokia Go module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ in_srl | string | b64encode }}"
      delegate_to: localhost
      when: ('srl' in group_names) and go

    - name: Use Resource modules to configure Arista EOS
      block:
        - name: Configure IP Routing
          arista.eos.eos_config:
            lines: ip routing

        - name: Configure interfaces
          arista.eos.eos_interfaces:
            state: merged
            config: "{{ interface }}"

        - name: Configure L3 interfaces
          arista.eos.eos_l3_interfaces:
            state: merged
            config: "{{ l3_interface }}"

        - name: Configure BGP
          arista.eos.eos_bgp_global:
            state: replaced
            config: "{{ bgp }}"
      when: ('eos' in group_names)

    - name: Run NVIDIA Go module on Systems without Go installed
      go_cvx:
        host: localhost
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ in_cvx | string | b64encode }}"
      when: ('cvx' in group_names) and not go

    - name: Run NVIDIA Go module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        input: "{{ in_cvx | string | b64encode }}"
      delegate_to: localhost
      when: ('cvx' in group_names) and go

- name: Second Play - Validate changes
  hosts: localhost
  gather_facts: false
  vars:
    go: true

  tasks:
    - name: Run Validate module on Systems with Go installed
      go_run:
        host: "{{ inventory_hostname }}"
      when: go
