name: AWS builder image (for testing environment)
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'ch12/**'

  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:

env:
  IMAGE_NAME: builder
  VERSION: 1.0.0

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ch12/testbed/.
          push: true
          tags: |
            ${{ github.repository_owner }}/$IMAGE_NAME:$VERSION
            ${{ github.repository_owner }}/$IMAGE_NAME:latest